### ISSUE TITLE
Request for GitHub migration: z3c.unconfigure

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#10]
As svn.zope.org is down, @mgedmin luckily offers a mirror at
https://zope3.pov.lt/trac/browser/z3c.unconfigure/trunk

Could anybody please migrate it to GitHub?

Thank you!

**Comment by mgedmin** [comment]
I can probably do it, but I don't remember exactly how and it'll take me a while to figure everything out.  I will do it if nobody else steps up.

**Comment by goschtl** [comment]
Hey Marius,

maybe you can drop a mail to Jim. He tries to migrate some stuff from us as
well this weekend...

HTH
Christian

Am Fr., 8. Nov. 2019 um 11:07 Uhr schrieb Marius Gedminas <
notifications@github.com>:

**Comment by icemac** [comment]
@jugmac00 I also have a copy of svn.zope.org lying around. I could import it on Wednesday next week.

**Comment by jugmac00** [comment]
@mgedmin 

The three days sprinting with @icemac were extremely packed with topics around migrating my company's intranet to Zope 4 (it kinda runs) and preparing the migration to Python 3. Did I say packed? Packed with **evil surprises** - that's how @icemac called it :-)

My interest in z3c.unconfigure is of 100% private / personal nature. So I cannot make the company I work for pay @icemac to do it.

So, if it is too much of a hassle, no problem. I can read the source code online via the link you gave me - and maybe learn a thing or two about my new hobby - diving into ZCA and ZCML :-)

On the other hand, I'd be happy for this project to live on, and maybe we can create a documentation how to migrate those old projects to GitHub, so anybody (also me) can do these in future.

**Comment by mgedmin** [comment]
I've found a README on my old laptop with instructions.

https://github.com/zopefoundation/z3c.unconfigure now exists.  I haven't touched anything under Settings as I don't remember if I need to.  If things like Travis CI don't work, holler and we'll try to ix them.

**Comment by icemac** [comment]
I edited the settings accordingly.

**Comment by mgedmin** [comment]
> I edited the settings accordingly.

It would be nice to have the correct settings for ZF repos documented somewhere.

**Comment by icemac** [comment]
@mgedmin https://github.com/zopefoundation/meta/settings/access can be used as blueprint.
