### ISSUE TITLE
Upload locally created wheels?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#107]
I was releasing version 4.5.1 of  `ExtensionClass` using `zest.releaser`.
Besides the sdist it created `ExtensionClass-4.5.1-cp37-cp37m-macosx_11_0_x86_64.whl` and uploaded it to PyPI.

Is this okay? I was not sure and deleted it immediately – as we have GHA to upload the wheels.
If it is not okay, is there a way to prevent `zest.releaser` from doing so? (Maybe via `create-wheel = false`?)

cc: @jamadden

**Comment by icemac** [comment]
Interestingly GHA created `ExtensionClass-4.5.1-cp37-cp37m-macosx_10_14_x86_64.whl` – it has a different MacOS version number, I am not sure if this matters.

**Comment by jamadden** [comment]
Once we have CI building wheels, I strongly recommend configuring zest.releaser to *not* upload wheels:
```conf
[zest.releaser]
 create-wheel = no
```

Locally built and uploaded wheels have [caused issues in the past](https://github.com/zopefoundation/persistent/issues/154).
