### ISSUE TITLE
Use PyPI tokens for CI package uploads

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/meta#109]
For packages containing C extension modules we build wheels for various architectures and OSes and upload them from our CI builders.  Some of those builds use username (zope.wheelbuilder) + password authentication, and we'd like to start using PyPI tokens instead.

We use three kinds of CI builders:

- Travis CI
- Appveyor
- GitHub Actions

### Travis CI

We ran out of credits so no Travis builds are running.  We can ignore these and wait for migration to GitHub Actions to complete.  We plan to change the zope.wheelbuilder account password to be more secure, so the old encrypted value in .travis.yml files will lose meaning.

### Appveyor

The procedure is:
- log in to PyPI.org as zope.wheelbuilder
- go to Account Settings (https://pypi.org/manage/account/)
- click Add API token
- Permissions: upload, Scope: Project "zope-foo"
- copy the token
- log in to Appveyor using your GitHub account 
- Account Settings -> Encrypt YAML (https://ci.appveyor.com/tools/encrypt)
- paste the PyPI token
- copy the encrypted `secure: ...` blob
- create a pull request that replaces the old secure: blob in appveyor.yml with the new one
- also please add a comment to the top of appveyor.yml mentioning who the contact persons are, e.g. https://github.com/zopefoundation/zope.security/blob/978ecadf5cb773844e4895bce42c463677cde936/appveyor.yml#L1-L2

Only the person who used their personal Appveyor account to set up Appveyor builds can do this.

Repositories set up by @mgedmin:
- [x] BTrees → https://github.com/zopefoundation/BTrees/pull/175
- [x] persistent → https://github.com/zopefoundation/persistent/pull/163
- [x] zodbpickle → https://github.com/zopefoundation/zodbpickle/pull/62
- [x] zope.container → https://github.com/zopefoundation/zope.container/pull/41
- [x] zope.hookable → https://github.com/zopefoundation/zope.hookable/pull/19
- [x] zope.i18nmessageid → https://github.com/zopefoundation/zope.i18nmessageid/pull/24
- [x] zope.index → https://github.com/zopefoundation/zope.index/pull/32
- [x] zope.interface -- https://github.com/zopefoundation/zope.interface/pull/244
- [x] zope.proxy → https://github.com/zopefoundation/zope.proxy/pull/45
- [x] zope.security → https://github.com/zopefoundation/zope.security/pull/77

Repositories set up by @dataflake:
- [x] AccessControl → https://github.com/zopefoundation/AccessControl/pull/112
- [x] Acquisition → https://github.com/zopefoundation/Acquisition/pull/47
- [x] ExtensionClass → https://github.com/zopefoundation/ExtensionClass/pull/32
- [x] Persistence → https://github.com/zopefoundation/Persistence/pull/25

### GitHub Actions

We already use PyPI tokens for our builds, stored in the TWINE_PASSWORD secret variable, managed via the GitHub UI for each repository.

- [x] BTrees
- [x] ExtensionClass
- [x] persistent
- [x] zope.interface

**Comment by icemac** [comment]
Thank you for brining this up and working on it. Maybe we could completely switch away from AppVeyor to GHA to build the Windows wheels. But I have no experience there and AppVeyor currently works, even though it is quite difficult to set it up using `meta/config`.

**Comment by mgedmin** [comment]
Side effect of creating all those tokens: https://github.com/pypa/warehouse/issues/9674

**Comment by dataflake** [comment]
@mgedmin Thanks for the detailed instructions. I went through those 4 packages that use my Appveyor account and created PRs.

**Comment by icemac** [comment]
Thank you for working on this issue. It seems to me that all the repos are updated now. Is this correct so the issue can be closed?

**Comment by dataflake** [comment]
I have created a page for www.zope.org that captures binary wheel information from this issue and https://github.com/zopefoundation/ExtensionClass/issues/30, take a look at https://github.com/zopefoundation/www.zope.org/pull/11/files
