### ISSUE TITLE
Python 3.8 wheels on PyPI

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/meta#11]
It would be nice to have Python 3.8 wheels for Windows at least (Linux users tend to have C compilers) published on PyPI for all zopefoundation packages that have extension modules.

I've been tackling this one by one, but there are more of the packages than I've remembered, so I've decided to file one tracking issue here.

Scope creep:
- building manylinux wheels always, not just for tags
- adding manylinux wheels to projects that don't build them
- switching from manylinux1 docker images to manylinux2010
- adding MacOS wheels to projects that don't build them
- avoiding MacOS twine upload problems on Python 3.5 due to TLS protocol mismatches

Out of scope because oh come on, please somebody else step up to do these I have enough work as it is:
- Python 3.8 on MacOS
- Zope 2 (or is it Zope 4 now)

Packages that have extension modules (found by doing a `grep twine */appveyor.yml` on all repos):

- [ ] AccessControl (I intend to ignore Zope 2/4)
- [ ] Acquisition (I intend to ignore Zope 2/4)
- [x] BTrees → https://github.com/zopefoundation/BTrees/issues/113, https://github.com/zopefoundation/BTrees/pull/114, https://github.com/zopefoundation/BTrees/pull/115
- [ ] ExtensionClass (I intend to ignore Zope 2/4)
- [ ] Persistence (I intend to ignore Zope 2/4)
- [x] persistent → https://github.com/zopefoundation/persistent/issues/117, https://github.com/zopefoundation/persistent/pull/118, https://github.com/zopefoundation/persistent/pull/119, https://github.com/zopefoundation/persistent/pull/120
- [x] zodbpickle → https://github.com/zopefoundation/zodbpickle/issues/50, https://github.com/zopefoundation/zodbpickle/pull/51, https://github.com/zopefoundation/zodbpickle/pull/52
- [x] zope.container → https://github.com/zopefoundation/zope.container/issues/28, https://github.com/zopefoundation/zope.container/pull/30 ([wheels](https://travis-ci.org/zopefoundation/zope.container/builds/610511507) [built](https://ci.appveyor.com/project/mgedmin/zope-container/builds/28780611))
- [x] zope.hookable → https://github.com/zopefoundation/zope.hookable/pull/13, https://github.com/zopefoundation/zope.hookable/pull/14 (wheels built)
- [x] zope.i18nmessageid → https://github.com/zopefoundation/zope.i18nmessageid/pull/17, https://github.com/zopefoundation/zope.i18nmessageid/pull/18 (wheels built)
- [x] zope.index → https://github.com/zopefoundation/zope.index/pull/27, https://github.com/zopefoundation/zope.index/pull/28  (wheels built)
- [x] zope.interface → https://github.com/zopefoundation/zope.interface/pull/145, https://github.com/zopefoundation/zope.interface/pull/146 ([wheels](https://travis-ci.org/zopefoundation/zope.interface/builds/610352389) [built](https://ci.appveyor.com/project/mgedmin/zope-interface/builds/28771018)), https://github.com/zopefoundation/zope.interface/pull/147, https://github.com/zopefoundation/zope.interface/pull/148 ([more](https://travis-ci.org/zopefoundation/zope.interface/builds/610447412) [wheels](https://ci.appveyor.com/project/mgedmin/zope-interface/builds/28777006))
- [x] zope.proxy → https://github.com/zopefoundation/zope.proxy/pull/32, https://github.com/zopefoundation/zope.proxy/pull/33 ([wheels](https://travis-ci.org/zopefoundation/zope.proxy/builds/610479338) [built](https://ci.appveyor.com/project/mgedmin/zope-proxy/builds/28778909))
- [x] zope.security → https://github.com/zopefoundation/zope.security/pull/64, https://github.com/zopefoundation/zope.security/pull/65 ([wheels](https://travis-ci.org/zopefoundation/zope.security/builds/610479778) [built](https://ci.appveyor.com/project/mgedmin/zope-security/builds/28778950))

**Comment by mgedmin** [comment]
Current status:

|                    |    2.7    |    3.5    |    3.6    |    3.7    |    3.8    |
| ------------------ | --------- | --------- | --------- | --------- | --------- |
| BTrees             | Lin---Win | Lin---Win | LinMacWin | LinMacWin | Lin---Win |
| persistent         | ---MacWin | ---MacWin | ---MacWin | ---MacWin | ------Win |
| zodbpickle         | LinMacWin | Lin---Win | LinMacWin | LinMacWin | Lin---Win |
| zope.container     | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.hookable      | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.i18nmessageid | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.index         | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.interface     | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.proxy         | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.security      | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |

(table generated with https://github.com/mgedmin/check-pypi-wheels).

Missing wheels:
- [ ] Python 3.8 for Mac OS: all packages
- [ ] Python 2.7 and 3.5 for Mac OS: BTrees
- [ ] Python 3.5 for Mac OS: zodbpickle
- [ ] manylinux (all Python versions): persistent

**Comment by mgedmin** [comment]
I'm done working on this.

**Comment by mgedmin** [comment]
Meanwhile things have progressed somewhat:

|                    |    2.7    |    3.5    |    3.6    |    3.7    |    3.8    |
| ------------------ | --------- | --------- | --------- | --------- | --------- |
| BTrees             | Lin---Win | Lin---Win | LinMacWin | LinMacWin | Lin---Win |
| persistent         | LinMacWin | Lin---Win | LinMacWin | LinMacWin | LinMacWin |
| zodbpickle         | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.container     | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.hookable      | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.i18nmessageid | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.index         | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.interface     | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.proxy         | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |
| zope.security      | LinMacWin | LinMacWin | LinMacWin | LinMacWin | Lin---Win |

We have a slight regression (persistent MacOS wheel for Python 3.5 failed to build), and also slight improvement (persistent has Python 3.8 MacOS wheels now).

Would anyone care to copy and paste the Mac OS 3.8 build snippet from persistent's .travis.yml to all the other packages?

**Comment by icemac** [comment]
@mgedmin zope.interface got Py3.8 MacOS wheels on master and 4.7 but it is not yet released. Should I change your table to add it there or what is the plan?

**Comment by mgedmin** [comment]
The table shows what's available to the users.  We could backport the travis changes to a temporary branch and hack out the "only tags" restriction to build an upload the missing wheels for the existing releases, but this is complicated and error prone.  We can wait for the next release or until a user complains.

Meanwhile I see zope.hookable and zope.i18nmessageid got Mac 3.8 wheels, and persistent even has Mac 3.9 wheels despite Python 3.9 not being out yet.  Let's hope 3.9 final won't break ABI compatibility with whatever alpha prerelease is out yet!

**Comment by icemac** [comment]
Okay, lets wait for the new releases to be made.
I am going to copy-paste the snipped from `zope.interface` to the other listed packages now.

**Comment by icemac** [comment]
I added the snipped to add 3.8 MacOS wheels for 
* zodbpickle
* zope.container
* zope.hookable
* zope.security

I removed 3.9 MacOS wheels from: (Let's wait until the final release.)

* zope.proxy

I think this issue can be closed again. Agreed?

**Comment by mgedmin** [comment]
> I think this issue can be closed again. Agreed?

Sure!
