### ISSUE TITLE
Please unarchive tempstorage

### ISSUE THREAD

**Issue by navytux** [zopefoundation/meta#116]
Hello up there,

Could you please unarchive https://github.com/zopefoundation/tempstorage repostitory?

We use it in our systems and today I hit and fixed the [issue](https://github.com/zopefoundation/tempstorage/issues/8) that was the reason for tempstorage archival. This way I would like to create corresponding pull request and fix it. Here is the fix commit: https://github.com/navytux/tempstorage/commit/34494fc0. I quote its description here for completeness.

Thanks beforehand,
Kirill

---- 8< ----
Fix loadBefore vs GC

TemporaryStorage uses

    ._index   {} oid -> serial
    ._opickle {} oid -> data

as data store for load. However for loadBefore

    ._conflict_cache  {} (oid,serial) -> (data, time)

is reused as data store.

That would be ok if that place would be treated as data store, but given
its primary purpose - as its name suggests - was originally to be a
cache to resolve conflicts, it is "logical" that entries in this cache
are garbage-collected when entry age becomes > gc threshold.

Only now there is a problem: if an object is committed once, and time
passes, corresponding entry in ._conflict_cache will be removed. And this
would manifest itself as

    - load(oid)  -> gives latest data for the object (obtained via ._index and ._opickle)

but

    - loadBefore(oid, @head)  -> gives POSKeyError

-> Fix it by always preserving latest object revision in
._conflict_cache from being removed on GC. 

The fix is important for systems that use ZODB5, or ZODB4-wc2[1] because
there ZODB.Connection switched from primarily using load to exclusively
using loadBefore.

/cc @icemac @mauritsvanrees @mgedmin @d-maurer @dwt @hannosch

Fixes: https://github.com/zopefoundation/tempstorage/issues/8
[1] https://lab.nexedi.com/nexedi/ZODB/commit/8e7eab33

**Comment by icemac** [comment]
I unarchived https://github.com/zopefoundation/tempstorage. Thank you for planning to work on this package.

**Comment by navytux** [comment]
Thanks, @icemac. I've followed up on https://github.com/zopefoundation/tempstorage/pull/16.
