### ISSUE TITLE
Replace `toml` by `tomllib`?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#118]
The `toml` project does not seem to be that alive. (See https://github.com/uiri/toml/pull/343 which could help us here but it has no comments – like many other PRs.)

According to https://github.com/pypa/pip/pull/10035 `pip` is switching to [tomli](https://pypi.org/project/tomli/) which even has support for version 1 of the TOML standard.

**Comment by dataflake** [comment]
I have no opinion on that, I don't use `toml` anywhere outside of this project. Either way is fine.

**Comment by icemac** [comment]
Even pep517 (the project to support `pyproject.toml`) now uses `tomli`, see https://github.com/pypa/pep517/blob/master/pyproject.toml.

I am going look into switching to `tomli` the next couple of days.

**Comment by icemac** [comment]
Python 3.11 will include a toml parser, so we could wait until its final release and then switch.

**Comment by dataflake** [comment]
That sounds like a great plan - anything that cuts reliance on external libraries is a win.

**Comment by icemac** [comment]
See https://github.com/zopefoundation/meta/blob/master/config/shared/toml_encoder.py if it can be removed or changed after switching to Python 3.11.

**Comment by dataflake** [comment]
I don't mind requiring Python 3.11 from now on to run the script.

**Comment by mgedmin** [comment]
+1 for depending on tomli with a `; pythonversion < "3.11"` constraint

+0.5 for depending on stdlib tomllib and requiring python 3.11, in which case I would also like the shebang to request python3.11 specifically, as the current `#!/usr/bin/env python3` will translate to 3.10 on my Ubuntu 20.10 system
