### ISSUE TITLE
Sphinx 4.0.3 has restored `force_decode`

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#119]
@jamadden wrote:
> Note that Sphinx 4.0.3 (released July 5) has [restored `force_decode`](https://github.com/sphinx-doc/sphinx/blob/939c7bb7ff7c53a4d27df067cea637540f0e1dad/CHANGES#L177), meaning that `repoze.sphinx.autointerface` again works.

_Originally posted by @jamadden in https://github.com/zopefoundation/zope.proxy/issues/46#issuecomment-880575317_

So we can change the requirement of `Sphinx < 4` to `Sphinx >= 4.0.3`.

**Comment by icemac** [comment]
Fixed in af45ce3b063d82a5aef886f2ce448a105aa8d82c without enforcing `Sphinx >= 4.0.3`

**Comment by jugmac00** [comment]
Afair the removal of `force_decode` was just postponed, so it will break again in Sphinx 5.

**Comment by icemac** [comment]
@jugmac00 Maybe we find a way to fix `repoze.sphinx.autointerface` until then.

**Comment by jugmac00** [comment]
🤞
