### ISSUE TITLE
Replace coveralls.io?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#14]
Coveralls lately behaves really strange, some examples of many oddities:

* drop in coverage by 1,7 % by changing some numbers in a text file, see https://github.com/zopefoundation/Zope/commit/15c1ed6c4bcca9cc895c7a54817fb2e5666cdecc
* drop in coverage by 5,3 % by changes in untested documentation, see  https://github.com/zopefoundation/Zope/pull/766
* As by today Coveralls tells me at the top of https://coveralls.io/github/zopefoundation/Zope that Zope has a coverage of 79 % but down the page there are nearly 85 % for `src/` shown.

These coverage numbers do not help at all, they are only a distraction.

I could imagine to replace coveralls.io by another coverage tool.
Are there any suggestions?

**Comment by jamadden** [comment]
I sometimes see the same issues locally, e.g., on persistent right now using tox the HTML report is often very wrong, even when produced from the same virtual environmenment. I don't know that it's an issue with coveralls so much as it is some underlying issue in newer versions of coverage (IIRC, the numbers started looking *interesting* with releases of coverage 5).

**Comment by mgedmin** [comment]
codecov.io is the only other coverage tracking tool I remember, but I haven't been sufficiently annoyed by coveralls.io problems to switch to it yet.

**Comment by icemac** [comment]
Currently coveralls.io does not make enough problems to have the need to switch.
