### ISSUE TITLE
Fix `DeprecationWarnings` in `unittest.*`

### ISSUE THREAD

**Issue by sallner** [zopefoundation/meta#143]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

As reported in https://github.com/zopefoundation/zope.security/issues/83, changes made in https://github.com/python/cpython/pull/28382 are raising a range of `DeprecationWarnings`.  

### What I did:

`tox -epy311`
See also https://github.com/zopefoundation/zope.security/issues/83#issuecomment-1072202619

### What to do:
Fix the issue maybe with help of `pre-commit` and `pyupgrade` after this proposal is implemented https://github.com/asottile/pyupgrade/issues/631

Fix the `DeprecationWarnings` in:
- [ ] [AccessControl](https://github.com/zopefoundation/AccessControl)
- [ ] [DateTime](https://github.com/zopefoundation/DateTime)
- [ ] [DocumentTemplate](https://github.com/zopefoundation/DocumentTemplate)
- [ ] [Products.CMFCore](https://github.com/zopefoundation/Products.CMFCore)
- [ ] [Products.CMFDefault](https://github.com/zopefoundation/Products.CMFDefault)
- [ ] [Products.CMFUid](https://github.com/zopefoundation/Products.CMFUid)
- [ ] [Products.DCWorkflow](https://github.com/zopefoundation/Products.DCWorkflow)
- [ ] [Products.GenericSetup](https://github.com/zopefoundation/Products.GenericSetup)
- [ ] [Products.MIMETools](https://github.com/zopefoundation/Products.MIMETools)
- [ ] [Products.MailHost](https://github.com/zopefoundation/Products.MailHost)
- [ ] [Products.PluggableAuthService](https://github.com/zopefoundation/Products.PluggableAuthService)
- [ ] [Products.PluginRegistry](https://github.com/zopefoundation/Products.PluginRegistry)
- [ ] [Products.Sessions](https://github.com/zopefoundation/Products.Sessions)
- [ ] [Products.ZMySQLDA](https://github.com/zopefoundation/Products.ZMySQLDA)
- [ ] [Products.ZSQLMethods](https://github.com/zopefoundation/Products.ZSQLMethods)
- [ ] [Products.ZopeVersionControl](https://github.com/zopefoundation/Products.ZopeVersionControl)
- [ ] [ZEO](https://github.com/zopefoundation/ZEO)
- [ ] [ZODB](https://github.com/zopefoundation/ZODB)
- [ ] [ZServer](https://github.com/zopefoundation/ZServer)
- [ ] [Zope](https://github.com/zopefoundation/Zope)
- [ ] [cipher.encryptingstorage](https://github.com/zopefoundation/cipher.encryptingstorage)
- [ ] [roman](https://github.com/zopefoundation/roman)
- [ ] [tempstorage](https://github.com/zopefoundation/tempstorage)
- [ ] [transaction](https://github.com/zopefoundation/transaction)
- [ ] [z3c.authenticator](https://github.com/zopefoundation/z3c.authenticator)
- [ ] [z3c.form](https://github.com/zopefoundation/z3c.form)
- [ ] [z3c.jbot](https://github.com/zopefoundation/z3c.jbot)
- [ ] [z3c.menu.ready2go](https://github.com/zopefoundation/z3c.menu.ready2go)
- [ ] [z3c.objpath](https://github.com/zopefoundation/z3c.objpath)
- [ ] [z3c.recipe.compattest](https://github.com/zopefoundation/z3c.recipe.compattest)
- [ ] [z3c.relationfield](https://github.com/zopefoundation/z3c.relationfield)
- [ ] [z3c.rml](https://github.com/zopefoundation/z3c.rml)
- [ ] [z3c.schema](https://github.com/zopefoundation/z3c.schema)
- [ ] [z3c.sqlalchemy](https://github.com/zopefoundation/z3c.sqlalchemy)
- [ ] [z3c.testing](https://github.com/zopefoundation/z3c.testing)
- [ ] [z3c.wizard](https://github.com/zopefoundation/z3c.wizard)
- [ ] [zc.intid](https://github.com/zopefoundation/zc.intid)
- [ ] [zc.recipe.testrunner](https://github.com/zopefoundation/zc.recipe.testrunner)
- [ ] [zc.zlibstorage](https://github.com/zopefoundation/zc.zlibstorage)
- [ ] [zc.zrs](https://github.com/zopefoundation/zc.zrs)
- [ ] [zdaemon](https://github.com/zopefoundation/zdaemon)
- [ ] [zodbpickle](https://github.com/zopefoundation/zodbpickle)
- [ ] [zope.app.appsetup](https://github.com/zopefoundation/zope.app.appsetup)
- [ ] [zope.app.authentication](https://github.com/zopefoundation/zope.app.authentication)
- [ ] [zope.app.container](https://github.com/zopefoundation/zope.app.container)
- [ ] [zope.app.form](https://github.com/zopefoundation/zope.app.form)
- [ ] [zope.app.http](https://github.com/zopefoundation/zope.app.http)
- [ ] [zope.app.pagetemplate](https://github.com/zopefoundation/zope.app.pagetemplate)
- [ ] [zope.app.publication](https://github.com/zopefoundation/zope.app.publication)
- [ ] [zope.app.testing](https://github.com/zopefoundation/zope.app.testing)
- [ ] [zope.authentication](https://github.com/zopefoundation/zope.authentication)
- [ ] [zope.browserpage](https://github.com/zopefoundation/zope.browserpage)
- [ ] [zope.browserresource](https://github.com/zopefoundation/zope.browserresource)
- [ ] [zope.component](https://github.com/zopefoundation/zope.component)
- [ ] [zope.configuration](https://github.com/zopefoundation/zope.configuration)
- [ ] [zope.container](https://github.com/zopefoundation/zope.container)
- [ ] [zope.copypastemove](https://github.com/zopefoundation/zope.copypastemove)
- [ ] [zope.datetime](https://github.com/zopefoundation/zope.datetime)
- [ ] [zope.dottedname](https://github.com/zopefoundation/zope.dottedname)
- [ ] [zope.dublincore](https://github.com/zopefoundation/zope.dublincore)
- [ ] [zope.formlib](https://github.com/zopefoundation/zope.formlib)
- [ ] [zope.i18n](https://github.com/zopefoundation/zope.i18n)
- [ ] [zope.index](https://github.com/zopefoundation/zope.index)
- [ ] [zope.intid](https://github.com/zopefoundation/zope.intid)
- [ ] [zope.location](https://github.com/zopefoundation/zope.location)
- [ ] [zope.proxy](https://github.com/zopefoundation/zope.proxy)
- [ ] [zope.publisher](https://github.com/zopefoundation/zope.publisher)
- [ ] [zope.renderer](https://github.com/zopefoundation/zope.renderer)
- [ ] [zope.security](https://github.com/zopefoundation/zope.security)
- [ ] [zope.site](https://github.com/zopefoundation/zope.site)
- [ ] [zope.sqlalchemy](https://github.com/zopefoundation/zope.sqlalchemy)
- [ ] [zope.tal](https://github.com/zopefoundation/zope.tal)
- [ ] [zope.testing](https://github.com/zopefoundation/zope.testing)
- [ ] [zope.testrunner](https://github.com/zopefoundation/zope.testrunner)
- [ ] [zope.traversing](https://github.com/zopefoundation/zope.traversing)
- [ ] [zope.untrustedpython](https://github.com/zopefoundation/zope.untrustedpython)

### What version of Python and Zope/Addons I am using:

Python 3.11a6

**Comment by mauritsvanrees** [comment]
Speaking from memory, I think the whole 'def test_suite' can be removed, except maybe in very special cases. Also in Python 2.7.

**Comment by icemac** [comment]
> Speaking from memory, I think the whole 'def test_suite' can be removed, except maybe in very special cases. Also in Python 2.7.

It depends: `zope.testrunner` has an auto-detect feature for unittest subclasses, but we still need `test_suite` for doctests. So in most of the cases `test_suite` could be removed.

**Comment by icemac** [comment]
This issue should have been fixed by running `meta/drop-legacy-python.py` as it runs `pyupgrade`.
