### ISSUE TITLE
Building wheels for macOS on ARM

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#166]
Right now all macOS wheels are explicitly limited to an x86_64 architecture. It would make sense to either find out if it's possible to build universal wheels on GHA, or to explicitly build aarm64 wheels.

Side note: Python 3.8 is the first Python version that builds as aarm64 on current Macs. Earlier versions do not support it at all.

**Comment by dataflake** [comment]
Update: I just noticed that Python 3.11 macOS wheels, which didn't fall under the rule that forces x86_64 as that only applies to Python 3.10, do indeed build universal wheels. The first such released wheel (AccessControl 5.6) appears to be fetched correctly and works.

**Comment by icemac** [comment]
@dataflake So we just have to create new releases and say that for newer Python versions we already have MacOS ARM support? So this ticked can be closed as solved?

**Comment by icemac** [comment]
Or do we have to set:

```
        env:
           MACOSX_DEPLOYMENT_TARGET: 10.9
           _PYTHON_HOST_PLATFORM: macosx-10.9-universal2
```

as you tried for `zope.security` before? (see https://github.com/zopefoundation/zope.security/commit/b08fc65a6fe465f5748a34bb81d4be69c0486810)

**Comment by dataflake** [comment]
The problem is actually deeper than that. The failing eggs have a few things in common:

- the wheel has a binary extension
- the wheel has dependencies that in itself have binary extensions
- the wheel pre-installs those dependencies to get at header files from those dependencies that are needed for compiling itself

Those binary wheels that maintain a copy of dependent header files in their own source tree, like AccessControl and a few others, do not have the issue. Only packages that want to download and install dependencies to get at header files do.

I still believe this is a setuptools issue where setuptools doesn't realize the dependency egg has already been created and then wants to create it again.

By the way, this is a blocker for Zope itself. A buildout run to install Zope with the updated egg versions does not work right now on my macOS/arm64 machine with that "folder not empty" failure.

Right now I am wondering if it isn't possible to get at those needed header files in a different way. Either install the eggs in a different directory tree, or not install them but just grab and unpack them.

**Comment by dataflake** [comment]
#173 attempts to fix the issue with a combination of changes for collecting build requirements beforehand and for building arm64, x86_64 and universal2 wheels at the same time. Keep your fingers crossed.
