### ISSUE TITLE
flake8 runs twice for zope-product config ?

### ISSUE THREAD

**Issue by perrinjerome** [zopefoundation/meta#180]
### What I did:

For example in Zope tests, flake8 runs twice:

https://github.com/zopefoundation/Zope/actions/runs/3732713088/jobs/6332527030

![image](https://user-images.githubusercontent.com/521510/208810229-fd31b0b5-bf2c-4307-9474-7a48c7260fd7.png)

here it is twice
https://github.com/zopefoundation/meta/blob/1ef8b9b8ae8311a7e79edb13d5086aed20bda382/config/zope-product/tox.ini.j2#L49-L50

this seems after https://github.com/zopefoundation/meta/commit/863bceecb48a88d769063e4dedce3fd77d2b6187 , before there was one line ( with `-` prefix to ignore return code ) for flake8-html and one line for flake8, but now it's just two lines for flake 8.

I feel this can be fixed by removing the first of the two lines.

It's really minor but since it's time to update all the repositories it might be a good time to fix this. 

### What I expect to happen:

flake8 run ony once

### What actually happened:

flake8 run twice

### What version of Python and Zope/Addons I am using:

zope https://github.com/zopefoundation/Zope/blob/bf10dc25b6dd857bc6bba273fc614784502d1493/tox.ini#L57-L58

**Comment by perrinjerome** [comment]
Hello @icemac can you take a look and tell me if I was missing something here ? thanks !

**Comment by dataflake** [comment]
You're not doing anything wrong, the `zope-product` template ran it twice. I smuggled a fix into PR #179 (see https://github.com/zopefoundation/meta/pull/179/commits/5dc7a26a6936d9a2579aa0d53da30ed6811b0930)

**Comment by perrinjerome** [comment]
Thanks @dataflake
