### ISSUE TITLE
manylinux wheel builds for Linux do not build Python 3.11 wheels

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#182]
It looks like the manylinux builds for Linux - both `i686` and `x68_64` - do not produce wheels for Python 3.11. Those are missing from PyPI and they are missing from the build artifacts of the GHA run, those `manylinux_manylinuxXXXX_ARCH_wheels.zip`. `aarch64` does build Python 3.11 wheels and those are published on PyPI.

**Comment by dataflake** [comment]
It looks like the docker images specified for the i686 and x86_64 manylinux builds are outdated - the last update to `manylinux2010_x86_64` was last August. No wonder there's no Python 3.11 available.

@icemac I don't know my the `2010` images were selected originally, is it safe to simply replace any occurrence of `manylinux2010` with `manylinux2014`? The corresponding i686 and x86_64 images are available and maintained.

**Comment by icemac** [comment]
According to https://github.com/zopefoundation/persistent/issues/179 it seems to be save. But I have no personal knowledge about the manylinux flavors at all.
