### ISSUE TITLE
In order to still support Python 2, do not pin Zope's master

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#19]
> Many Zope products that haven't been updated in a while still reference Zope `master` for their version pins, but all those that still support Python 2 must change that to reference Zope `4.x` since `master` has no Python 2 support anymore.

From a quick grep over Zopefoundation's repos, there are only 2 products left to be fixed - I plan to to during today's sprint.

_Originally posted by @jugmac00 in https://github.com/zopefoundation/meta/issues/15#issuecomment-627657475_

**Comment by jugmac00** [comment]
cf https://github.com/zopefoundation/Products.ExternalMethod/issues/8

**Comment by dataflake** [comment]
Pin versions-prod.cfg from the 4.x branch and also add versions.cfg to prevent issues with non-core eggs, like we had with BeautifulSoup or zipp in some packages.

**Comment by jugmac00** [comment]
```
❯ all-repos-grep https://zopefoundation.github.io/Zope/releases/master/versions-prod.cfg
/home/jugmac00/Repos/zopefoundation/DocumentTemplate:buildout.cfg:    https://zopefoundation.github.io/Zope/releases/master/versions-prod.cfg
/home/jugmac00/Repos/zopefoundation/Zope:docs/zdgbook/GettingStarted.rst:  extends = https://zopefoundation.github.io/Zope/releases/master/versions-prod.cfg
/home/jugmac00/Repos/zopefoundation/Zope:docs/zdgbook/GettingStarted.rst:  extends = https://zopefoundation.github.io/Zope/releases/master/versions-prod.cfg
```
So, there is only Zope itself left and DocumentTemplate, and both are Python 3 only on master. So we are all good now.
