### ISSUE TITLE
Organization-wide community health files

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#2]
There is a new feature on GitHub which allows to have organisation wide README, CONTRIBUTING, SUPPORT, CODE_OF_CONDUCT, ISSUE_TEMPLATE(S), or PULL_REQUEST_TEMPLATE(S).

Maybe this could be an idea for zopefoundation, too.

Details see https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

**Comment by freddrake** [comment]
Given the Zope Foundation being subsumed by the Plone Foundation, should we hold off until that's done, and deal with that in the larger context?

I don't know if the PF's plan is to migrate the ZF packages into the PF organization, or to simply be the supporting organization for both collections of packages on GitHub.

**Comment by dataflake** [comment]
Hey @freddrake, nice to hear from you. IMHO there's no harm setting something like that up with the current de-facto standards. We have no idea how long the foundation merge process will take. I doubt the packages will physically move between GitHub organizations, though.

**Comment by freddrake** [comment]
Hey @dataflake!  I've heard nothing about a specific timeline, so presume the legal team is hard at work, waiting for government response to paperwork.

Merging the GitHub organizations would be painful, given all the links to "zopefoundation" repository artifacts.

**Comment by dataflake** [comment]
This was already taken care of as part of #21
