### ISSUE TITLE
Document what the different GitHub teams are about

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#20]
At https://github.com/orgs/zopefoundation/teams there are 5 different teams.

I and also others do not know what the teams are about.

e.g. what is the difference between Administrators and Maintainers?

Also, who has access to Travis or Coverage.io services?

Ideally, there would be also some documentation about how to get into one of these teams. And also, when somebody should be excluded, e.g. no longer active (for x years).

**Comment by mgedmin** [comment]
> Also, who has access to Travis or Coverage.io services?

/me raises hand, although AFAIU both use GH for authentication so access level depends on GH group membership.

I also have access to GitHub settings for all the repos.  And Appveyor (AFAIK all the ZF repos that have extension modules and use Appveyor have it configured with my personal free account).

PyPI access is easier to track: it's displayed on every PyPI page.

There's also readthedocs where I have access for a couple of packages only.

**Comment by jugmac00** [comment]
@icemac Maybe you could write a couple of lines during the next sprint?

**Comment by icemac** [comment]
The question would be: where to write down this documentation.

**Comment by jugmac00** [comment]
I think this would be a good place: https://docs.zope.org/developer/index.html

**Comment by dataflake** [comment]
That's www.zope.org, I just added https://github.com/zopefoundation/www.zope.org/issues/9 to make it more obvious that docs.zope.org is an alias only.

The repo for that website is at https://github.com/zopefoundation/www.zope.org

**Comment by icemac** [comment]
I added descriptions to the teams at https://github.com/orgs/zopefoundation/teams and removed a team which was not needed there by giving the members permissions directly on the repository. (I was surprised that teams can only be created at organization level, but that seems to be the way GitHub works.)

**Comment by jugmac00** [comment]
Awesome!
