### ISSUE TITLE
When to start dropping support for end-of-life Python versions?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#200]
According to https://peps.python.org/pep-0537/#lifespan: "As of 2023-06-27, 3.7 has reached the [end-of-life phase](https://devguide.python.org/devcycle/#end-of-life-branches) of its release cycle."

So my question is: Can we come up with a decision/formula when to drop support for Python versions which are end of life? Should we begin to phase it out when it goes into end-of-live or wait some time (a month, half a year, a year, …)?

Any opinions?

**Comment by dataflake** [comment]
I think this is one of those issues where everyone has their own policies, there is no "one size fits all" approach. My own personal opinion: I would drop it whenever it is convenient after EOL status has been reached. Convenient means whenever someone touches a package for some other reason. I wouldn't start yet another round of updates just for that alone.

In practical terms that means dropping it from the `meta` scripts and templates soon, and then any packages that gets updates will have it applied automatically.

**Comment by dataflake** [comment]
P.S.: In this specific case we have it relatively easy: Plone 6 only supports Python 3.8-3.11, anyway, so there's a lot less people who would be surprised or affected in a negative way.

**Comment by mauritsvanrees** [comment]
For the record, Plone 5.2 supported Python 3.7 until now, but we already stopped testing with it this month, and in July I will do a release where we officially drop support.
But we will try not to break it.  For example I definitely do **not** want to add `python_requires>=3.8`.  Anyway, any changes to zope packages are unlikely to affect Plone 5.2, as it uses Zope 4.

Question: when an individual package like `zope.interface` drops support for Python 3.7, will that be a major release?

For the Zope package itself, a major release would not make much sense: we would then have a major Zope release every year.  But Zope 5.8 already drops support for Python 3.6 in a minor release, so it makes sense to keep doing it that way.

**Comment by dataflake** [comment]
I would also call a change in supported Python versions a major release for packages other than Zope. For Zope we already decided it's OK to do that in a minor release.

**Comment by icemac** [comment]
Dropping support for a Python version next to the end of life of that version via `meta/config` means for me: When that package gets released (I support releasing it as a new major release.), all packages depending on it will automatically no longer support that Python version. So we should start dropping support at the leaves (i. e. Zope) to make it clear that individual packages no longer need to support that Python version.

Dropping support for a Python version means for me:
* running `pyupgrade` to upgrade the syntax to the new minimum Python version
* updating `python_requqires` in `setup.py` to be explicit instead of saying: It might still run but we do not test it anymore. – If someone has to use an older Python version they can stick with the older version of the package.
* A release does not have to be created immediately as dropping support for a Python version does not add any value for the user. It can be released together with the update to the next new Python version if there are any changes.

**Comment by gforcada** [comment]
For what is worth, my own 5 cents: I like the lazy/on-demand approach, given that we already transitioned all packages to python 3, and moreover, a given package now support 3.7 to 3.11 (that's 5 python releases), I'm more on the fence of making having to create major releases at any drop.

A probable scenario: next week lands a bugfix in `zope.interface` and at the time of releasing, python 3.7 support is dropped, so `zope.interface` 7.0 is released with only 2 entries:

- drop python 3.7 support
- minor/big bugfix

As Python is in a yearly cadence, for the most common packages that get fixes, it will mean, at least, a major release per year as well.

Given the 5 years cadence wouldn't make sense to _force_ a major release only when the _original_ list of 5 python versions are all of them deprecated?

i.e. `zope.interface` `6.0` was released March 17th 2023, so at that time it already supported `3.7` to `3.11`. If no breaking changes happen, only until `3.11` is [support is dropped](https://peps.python.org/pep-0664/), __October 2027__, we should force a new major release of `zope.interface`.

Release numbers are only that, a number, but seeing major releases that only drop python versions, that most probably no one is using (given that there are 4 other stable newer versions of python) feels a bit too much too me.

Maybe that was more than 5 cents 😆

**Comment by dataflake** [comment]
So a year has passed and the meta templates still have Python 3.7 support. I will go ahead now and do the following:

- merge https://github.com/zopefoundation/meta/pull/217 to remove Python 3.7 from the meta templates
- apply it to Zope itself because as @icemac says that's a good general sign that dependencies may drop 3.7 as well
- declare this a minor release for Zope. At least for Zope we already decided a while ago that adding/dropping Python version support is no reason for a major release

Other packages may drop 3.7 support later, meaning whenever one of us touches it and re-runs the configuration script.

My opinion on a general policy for when to drop a Python version: I don't think it makes sense to declare some fixed date like "as soon as that version is EOL" or "one year later" etc. That just creates additional work without clear benefit. In the case of Zope my own wish to stop supporting Python 3.7 grew with every release where I had to add more version exceptions for Python 3.7. It was a matter of "I'm tired of workarounds, let's just pull the trigger".

**Comment by icemac** [comment]
I think it is a good time to remove Python 3.7 support now. Python 3.8 will be EOL in October this year, so removing support for oder versions will probably become something like adding support for newer versions but with less effort.

**Comment by icemac** [comment]
We are actively removing Python 3.7 support and `update-python-support.py` provides support to do this semi-automatically and can easily be adopted for other Python versions.

So I am closing this issue as successfull. Thank you to everyone who has contributed.
