### ISSUE TITLE
Improve development guidelines

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#21]
The current page ( https://www.zope.org/developer/becoming-a-committer.html ) is very minimal.

Also, it is not linked or at least not very present from all our repositories.

Info, which is missing....
- merge the pr yourself
- possibly do not use mocks
- write a test (or not)
- use tox
- run linters before pr
- which test runner we use
- common test commands, e.g. how to run all vs how to run a single test
- and many more unwritten "laws"

**Comment by dataflake** [comment]
A contributor agreement is not the place to enforce things like coding standards, it's about assigning copyright and similar legal issues.

This page collects at least some of the information you're talking about: https://www.zope.org/developer/development-culture.html

**Comment by jugmac00** [comment]
As from time to time, new possible contributors show up at GitHub, I'd like to have one single page from where they could find all necessary informations.

Those informations would include both at least a link to the contributors agreement and to common expectations we have (see above).

As @icemac is currently working on the "config tool", it would be a nice idea to include a `CONTRIBUTING.md` to all packages - which then GitHub shows automatically when you create a new issue etc.

Any opinions on this?

**Comment by mgedmin** [comment]
IIRC GitHub allows organization-wide CONTRIBUTING.md etc. files, which should be easier to keep up-to-date without creating a bazillion pull requests after every change.

https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file:
> You can create default community health files, such as CONTRIBUTING and CODE_OF_CONDUCT. Default files will be used for any public repository owned by the account that does not contain its own file of that type.
