### ISSUE TITLE
Delete Travis for archived projects

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#23]
ie https://github.com/zopefoundation/Products.ZCTextIndex is archived, but https://travis-ci.org/github/zopefoundation/Products.ZCTextIndex still shows as broken in the Zopefoundation overview.

**Comment by jugmac00** [comment]
https://travis-ci.org/github/zopefoundation/cipher.googlepam

**Comment by jugmac00** [comment]
https://travis-ci.org/github/zopefoundation/zc.zkzeo

**Comment by mgedmin** [comment]
@icemac suggested that I hide archived repositories from https://zope3.pov.lt/py3/travis.html.  This is a good idea.

If you'd like to speed this process along, feel free to create a PR in https://github.com/mgedmin/ztk-py3-status

**Comment by jugmac00** [comment]
https://travis-ci.org/github/zopefoundation/zope.html

**Comment by mgedmin** [comment]
> @icemac suggested that I hide archived repositories from https://zope3.pov.lt/py3/travis.html.

This is now implemented, but I had to Ctrl+Shift+Reload to force my browser to re-fetch the json files.

(The cron script runs daily, so if you archive a repo and continue to see the package, that's why.)

**Comment by jugmac00** [comment]
Thank you very much!

Still, I think it's a good idea to deactivate those archived versions also on Travis, as they still show up there... and maybe even run weekly? Not sure about that.

**Comment by icemac** [comment]
@jugmac00 Is it possible on TravisCI to see if a package is archived?

**Comment by icemac** [comment]
To answer my question: No, it is not possible.

**Comment by icemac** [comment]
I did the manual task to walk trough all archived repos and deactivated them on TravisCI.
Feel free to create a new ticked for newly archived repos which are still active on TravisCI.

**Comment by mgedmin** [comment]
@icemac how do you deactivate a repository on TravisCI?  I was poking around the other day and couldn't find this option.  (I had to settle for disabling builds for pushes and builds for pull requests, which I think leaves the repo itself visible on the dashboard.)

**Comment by icemac** [comment]
@mgedmin If you did not already found this yourself: At https://travis-ci.org/account/repositories is a switch to disable a certain repository. (This is the "Settings" link in the profile menu.)
