### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by reinout** [zopefoundation/meta#230]
While at the birthday party of @mauritsvanrees I discovered the existence of plone/meta and zopefoundation/meta. Hurray! I was thinking about something similar for use at my workplace. But the zope/plone "meta" has a couple of better ideas than what I myself was thinking about.

So I want to borrow and copy some stuff but... there's no license file :-) Can I treat it as "public domain" or "bsd/mit"? I don't know yet whether I'll just be using the idea or whether I'm also going to be copying actual code. But I just started my repo and got asked by github whether I had a license in mind.

**Comment by dataflake** [comment]
No license at all is bad because it makes people speculate how they can use it. The code should be ZPL-licensed like all other repositories here.

**Comment by reinout** [comment]
Speculating was just what I was doing :-) That's why I asked.

I completely forgot about the ZPL. Logical to use that. I'll have to look up what the terms are. Long time ago :-)

**Comment by reinout** [comment]
Thanks for the quick fix!
