### ISSUE TITLE
Issues with manylinux aarch64 for Python 3.13

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#240]
Testing Python 3.13-based wheels on manylinux/aarch64 currently fails, see https://github.com/zopefoundation/zope.interface/actions/runs/9102178342/job/25021162232.

Looking at the output the first thing I am wondering about is why aarch64 is handled differently in the `.manylinux-install.sh` script. Unlike other platforms it explicitly installs `tox` and runs the tox tests:

```
        if [ `uname -m` == 'aarch64' ]; then
          cd /io/
          ${PYBIN}/pip install tox
          TOXENV=$(tox_env_map "${PYBIN}")
          ${PYBIN}/tox -e ${TOXENV}
          cd ..
        fi
```

Is that because none of us can really test Linux/aarch64 locally?

Secondly, this fails on Python 3.13. (side note: the script should be more fault-tolerant and not fail entirely when one build/test fails)

Unlike earlier Python versions, Python 3.13 actually has **two different interpreters** on those manylinux2014 images that are both tested by the script, one a standard compile with GIL, the other free-threaded with no GIL because that's a new feature for 3.13. The non-GIL version fails during the zope.interface wheel installation for testing claiming the wheel is not compatible with the running architecture. The wheel actually builds fine in a preceding step.

I am wondering if the script should skip the no-GIL version. I have no idea how a free-threaded version would interact with any of our packages.

**Comment by icemac** [comment]
+1 from me to not test no-GIL Python now. See https://github.com/zopefoundation/zope.interface/pull/297 for the changes which are necessary to port that package to be able to run on no-GIL - this is way beyond my C knowledge.

Regarding the tests: Linux is tested in the Ubuntu jobs but not for aarch64, so it is tested separately in its manylinux job.
