### ISSUE TITLE
GHA step naming

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#245]
The manylinux steps on GHA contain a Python version name (currently 3.9) but they build and/or test for all supported Python versions so the name is confusing. @icemac Is it OK if I at least change the name to drop the Python version?

**Comment by dataflake** [comment]
Another suggestion: The publicly visible names also include the specific GHA runner description, so whenever those change all packages must be touched to fix the branch protection rules. The specific runner name, like `ubuntu-latest`, isn't interesting to package users, only to us as maintainers of test matrices.

I suggest renaming all those steps to be more generic and include the Python version and a simple moniker added like Linux, macOS or Windows.

**Comment by dataflake** [comment]
I did a little research and don't see how those names can be influenced. There's no way to use an aliased "friendly" name for the information GH displays.

**Comment by icemac** [comment]
@dataflake Thank you for your investigation. I also would have liked to change the names as updating requires changing the branch protection but this is now less of a hassle as we can do it automatically.
