### ISSUE TITLE
Pip deprecation warning on editable install

### ISSUE THREAD

**Issue by dwt** [zopefoundation/meta#266]
### What I did:

```shell
# create a venv somehow
$ pip install --editable 'git+https://github.com/zopefoundation/Zope.git@master#egg=Zope'
[…]
  DEPRECATION: Legacy editable install of Zope from git+https://github.com/zopefoundation/Zope.git@master#egg=Zope (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
[…]
$ python --version
Python 3.12.5
$ pip list | grep -E 'pip|wheel|setuptools'
pip                     24.2
setuptools              73.0.0
wheel                   0.44.0
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
```

### What I expect to happen:

This should install without warning

### What actually happened:

The warning that is displayed above. I'm not quite sure yet I understand this warning correctly, but what I read sounds like switching from setup.py to pyproject.toml could solve this?

### What version of Python and Zope/Addons I am using:

See above

This warning and the linked GitHub issue, seems to suggest that  pip 25 (soonish) might break editable installs of Zope.

Is that an assessment you guys share? If so, is this the point to switch to a pyproject.toml based workflow for Zope?

**Comment by icemac** [comment]
Adding these three lines to a `pyproject.toml` should be possible here in `meta/config`.
@dwt I'll not be unhappy if you'd come up with a PR.
