### ISSUE TITLE
Question on usage of `PURE_PYTHON`

### ISSUE THREAD

**Issue by perrinjerome** [zopefoundation/meta#283]
## PROBLEM REPORT or QUESTION

It's not clear to me what is the "convention" over using `PURE_PYTHON`. 

The github actions are generated with `PURE_PYTHON=1` set only for "Run tests with C extensions" step:

https://github.com/zopefoundation/meta/blob/e07f139cb603e6d3e50590b750b337225244fe20/config/c-code/tests.yml.j2#L300

The tox.ini is generated to set environment variable `PURE_PYTHON=1` for "pure" cases and `PURE_PYTHON=0` for "non pure"

https://github.com/zopefoundation/meta/blob/e07f139cb603e6d3e50590b750b337225244fe20/config/c-code/tox.ini.j2#L3

Some code, for example [testZopeSecurityPolicy from AccessControl](https://github.com/zopefoundation/AccessControl/blob/4779653c918d294211823365675fd0e5de105a58/src/AccessControl/tests/testZopeSecurityPolicy.py#L775-L777) just check `os.environ.get('PURE_PYTHON')`, which is true in python if `PURE_PYTHON` is set to `"0"`. 

In some other places, for example [this zope.index test](https://github.com/zopefoundation/zope.index/blob/4238673a61a75cfefc73103f1390a92f501c938a/src/zope/index/text/okapiindex.py#L203) use `int(os.environ.get('PURE_PYTHON', '0'))`.

### What I did:

Run AccessControl tests with `tox -e py`

### What I expect to happen:

C code and python code to be tested

### What actually happened:

Only python code is tested because of `os.environ.get('PURE_PYTHON')`

### What version of Python and Zope/Addons I am using:

N/A

---

I'm not sure what is the best fix, probably packages can be changed to use `int(os.environ.get('PURE_PYTHON', '0'))` everywhere ?

**Comment by dataflake** [comment]
This is an issue with the package in question, in this case AccessControl, and should be filed there. Clearly, any test that considers the environment variable to have a truth value when it is set to a string `"0"` is bad.

**Comment by perrinjerome** [comment]
Thank you for clarifying, this was also my impression. I'll take care of fixing in AccessControl now by using `int()`.

I looked through https://github.com/search?q=org%3Azopefoundation+PURE_PYTHON+language%3APython&type=code&p=2&l=Python ,
https://github.com/zopefoundation/zope.proxy/blob/cbb23c424826d89538b90bb17dc35d48bacc356a/src/zope/proxy/__init__.py#L483 and https://github.com/zopefoundation/zope.security/blob/1b6affb836b0f0259c799b148fca1492bce4cde4/src/zope/security/_compat.py#L22 also look suspicious. I'll fix those two as well and close this issue.
