### ISSUE TITLE
Change policy to merge your own PRs

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#285]
New contributors seem no longer to get the right to merge. (See also zopefoundation/roman#22.)
Should we change our policy that you should merge your own PRs after review?
When merging a PR of another contributor we could/should check whether the contibutor shows up as member (right side at the top of the PR).

Is this policy written anywhere so we have to change a document or is this only an un-written policy?

**Comment by dataflake** [comment]
I talked to Paul Roeland who instituted the in-between step that will not give new contributors write access immediately. He copied the approach they used on the plonefoundation side. Apparently they have fought for a long time with people who sign the agreement and then abuse the privilege for homework assignments or really low-quality contributions. Now that I have talked to him I think https://github.com/zopefoundation/roman/pull/22 might have been such a case.

I do not know if their polict is written anywhere. I am in favor of changing our policy. I always thought it was kind of silly to surprise newcomers by telling them "you must merge yourself", it is always a surprise to them and we must explain it again and again.

Personally, once it is becoming obvious someone is a recurring contributor (a very rare case like we all know), I would just informally encourage them to merge themselves, like a "badge of honour" and if they are still in the "Fresh Contributor" group move them over to "Contributor".

**Comment by icemac** [comment]
At least our `Developer guidelines` say that you cam merge your PR yourself:
https://github.com/zopefoundation/www.zope.org/blob/5b6e9693dab830f55d1e024360b2780f115614ba/docs/developer/guidelines.rst?plain=1#L37-L38

**Comment by icemac** [comment]
+1 for changing our policy as it confuses contributors (even people which have been contributing for years in Plone repositories) and it is way faster to click "merge" than explaining again an unnecessary and unexpected step to the changes into merged.
So an approval should mean: just merge it afterwards (as the reviewer) or wait for others to review if you are not completely sure.

**Comment by icemac** [comment]
> Sounds good to me. I can change the docs tomorrow and update the website if you like.

👍 Thank you for volunteering.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2024-10-16 09:01 -0700:
>I considered this task as a discussion that leads to an agreement so I did not make any changes yet.

Have we made bad experience with new contributors getting write
access immediately?

If not, I would not change this: based on it, it has been quite
easy to win new contributors: you want a fix, become a contributor
and fix it yourself.

**Comment by dataflake** [comment]
We are following policy set by the Plone project and Paul Roeland told me they have plenty of experience with low-quality submissions and abuses of trust for new contributors. This appears to be a recent phenomenon. I think his conclusions and his remedy make sense. The only thing that will change for new contributors is that they cannot merge themselves. And as Michael and I have pointed out several times in the past, this self-merge policy always leads to confusion and the need to explain it again and again. It saves work and frustration if an established contributor just hits the merge button instead of waiting for the novice contributor to do it. So I am in favor.

**Comment by dataflake** [comment]
I have added a PR that contains some other cleanups as well. Due to time constraints I will merge and rebuild the website before 19:00 tonight, even if no one comments, I am going on vacation tomorrow early morning.
