### ISSUE TITLE
config tool: does not delete `test_suite` in setup.py

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#30]
As I understand `test_suite='zc.zdaemonrecipe.tests.test_suite',` was only necessary for calling the tests via the deprecated `python setup.py tests` call.

The config tool uses zope.testrunner, which does not need this entry point, right?

**Comment by mgedmin** [comment]
That's correct.

**Comment by mgedmin** [comment]
Two exceptions exist that I know of:
- zope.testrunner cannot really use itself, so it uses `python setup.py test`.
- zope.interface is a dependency of zope.testrunner, so to avoid dependency loops it also avoids relying on zope.testrunner and uses `python setup.py test`.

setup.py test is deprecated in setuptools, but I don't think there are plans to actually remove it any time soon.

All other packages should not be using or supporting `setup.py test`.  (It's possible that other exceptions with good reasons might exist, and I just don't know about them.)

**Comment by jamadden** [comment]
zope.interface [uses](https://github.com/zopefoundation/zope.interface/blob/master/tox.ini#L15) the standard library [python -m unittest discover](https://github.com/zopefoundation/zope.interface/blob/255db9d3c0ea7a5016e3c87644c23fca6eda9a7d/.travis.yml#L98) command. It dropped 'setup.py test' some time ago (although by default I think that does basically the same thing).

**Comment by icemac** [comment]
Duplicates #260.
