### ISSUE TITLE
config tool: coverage call failed

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#31]
When I worked on zc.zdaemonrecipe the config tool generated a coverage call like
`coverage run -m zope.testrunner --test-path=src []`.

The src thing left aside (I changed it to zc), this still did not work until I deleted the --test-path option.

So this worked:
`coverage run -m zope.testrunner`

I never use coverage, only pytest-cov, so I have no clue how to configure coverage correctly.

```
coverage run-test: commands[0] | coverage run -m zope.testrunner --test-path=zc
Test-module import failures:

Module: zdaemonrecipe.tests

ModuleNotFoundError: No module named 'zdaemonrecipe'



Test-modules with import problems:
  zdaemonrecipe.tests
Total: 0 tests, 0 failures, 1 errors and 0 skipped in 0.000 seconds.
Coverage.py warning: No data was collected. (no-data-collected)
ERROR: InvocationError for command /home/jugmac00/Repos/zopefoundation/zc.zdaemonrecipe/.tox/coverage/bin/coverage run -m zope.testrunner --test-path=zc (exited with code 1)
```

**Comment by mgedmin** [comment]
This has nothing to do with coverage, it's a zope-testrunner thing.  The correct --test-path for src-less packages is `.`.

It might result in zope.testrunning picking up more tests than it should.  Another reason to use src/ layouts everywhere...

**Comment by dataflake** [comment]
The repository for `zc.zdaemonrecipe` has been archived a while ago, so this issue is obsolete.
