### ISSUE TITLE
Travis changes billing options - especially for macOS builds

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#39]
see https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

I read the announcement twice, but I am still unsure what the change means for us, especially as there is no mention whether the free build minutes (which we would need for macOS), are monthly or one time only.

Also, they mention we could apply for free minutes.

These are presumably our repositories with macOS builds...
```
❯ all-repos-grep --repos-with-matches MacPython -- '.travis.yml'
output/zopefoundation/BTrees
output/zopefoundation/persistent
output/zopefoundation/zodbpickle
output/zopefoundation/zope.container
output/zopefoundation/zope.hookable
output/zopefoundation/zope.i18nmessageid
output/zopefoundation/zope.index
output/zopefoundation/zope.interface
output/zopefoundation/zope.proxy
output/zopefoundation/zope.security
```

[How to use all-repos-grep](https://github.com/jugmac00/til/blob/master/zope/how-to-update-all-zopefoundation-repositories-at-once.md)

**Comment by icemac** [comment]
See #38 for my thoughts about this billing change.

**Comment by jugmac00** [comment]
I think one issue is enough :+1:
