### ISSUE TITLE
Infrastructure to set up services for many repositories at once

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/meta#4]
I would like to be sure every zopefoundation repository that has a .travis.yml is enabled on Travis CI.

I would also like to be sure that every zopefoundation repository that uses coveralls is enabled on coveralls.io.

I would also like to add cron jobs for every repository so we can notice regressions as the ecosystem moves forwards (and e.g. drops support for older Python versions).  Periodically I go through all the failures I see at https://zope3.pov.lt/py3/travis.html?filter=zope., but that doesn't tell us much if the last build was months ago.

There's zope.githubsupport that can use the GitHub API to set some things up (like GitHub hooks to tell Travis about pushes), but (1) it's not very well documented, and (2) it has had bugs in the past that resulted in [semi-broken repositories](https://github.com/zopefoundation/zope.githubsupport/issues/1) that would ignore pull requests.

Do we build upon it, or do we search for alternative solutions?

**Comment by icemac** [comment]
That's hard to decide. I'd personally probably try with the things we already have first and look for alternatives second if our existing tools are too bad.

**Comment by icemac** [comment]
It would be nice to have a branch protection rule for `master` in each repository which prevents from force pushes to `master` and from deleting this branch.

**Comment by icemac** [comment]
There is now `meta/config`, in my opinion it serves the needs well enough.
Regarding branch protection: GitHub now tells about missing branch protection when I open the page of a repository in the browser, so I am adding it manually whenever it pops up.
