### ISSUE TITLE
Remove wiki here

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/meta#41]
@icemac the wiki in this repository has a single page about removing Python 2 support. I have migrated that into https://www.zope.org/developer/python2.html#how-to-drop-support and would like to remove the wiki page here. IMHO we should disable the wiki as well so no one is tempted to use it as documentation resource.

**Comment by icemac** [comment]
Thank you for migration the wiki to the documentation.
I disabled the wiki in the settings and remove a link from the readme.
