### ISSUE TITLE
meta/config for packages with C code

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#63]
See https://github.com/zodb/perfmetrics/blob/master/.github/workflows/tests.yml as an inspiration how to build binary wheels.

**Comment by icemac** [comment]
See https://github.com/zopefoundation/persistent/pull/159 for an example in zopefoundation land.

**Comment by jugmac00** [comment]
Repos with C files

https://github.com/zopefoundation/meta/issues/69#issuecomment-789591307

**Comment by icemac** [comment]
I am now working on this ticket.

**Comment by icemac** [comment]
Fixed by #94.
