### ISSUE TITLE
issues with the upcoming tox version

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#66]
Hi,

currently, tox gets completely rewritten - the new version 4 is announced for the begin of May 2021.

I run tox4-pre on my dev box for all the repositories I work on for quite some time already.

I reported already a bunch of issues, which all got fixed super quick.

On the weekend I took some time, and once again I used `all-repos`, but this time not to create mass pull requests, but to run tox4-pre on all active Zope (and Plone) repos.

> tox 4 alpha 6 on 288 Zope repositories, 17 without tox, 62 successful, 208 broken builds, 1 excluded

While this sounds bad, it's not - and there is lots of time to report and fix the issues. Also, this will boil down to only a couple of issues, which just happen in  a lot of repositories.

The most common one is `re.error: unterminated character set at position 0?` which gets caused by `zope.testrunner` during the test collection.

The most annoying error was the one in `zopetoolkit` which caused memory exhaustion due to an endless `setuptools` update loop.

That is how I did it..

https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/

And this is the result:

```
problems: 208 ['zopefoundation/Products.PythonScripts', 'zopefoundation/ZODB', 'zopefoundation/transaction', 'zopefoundation/persistent', 'zopefoundation/zope.event', 'zopefoundation/zope.i18nmessageid', 'zopefoundation/zope.exceptions', 'zopefoundation/zope.deprecation', 'zopefoundation/zope.schema', 'zopefoundation/zope.configuration', 'zopefoundation/zope.component', 'zopefoundation/zope.copy', 'zopefoundation/zope.hookable', 'zopefoundation/zope.location', 'zopefoundation/zope.proxy', 'zopefoundation/zope.security', 'zopefoundation/zope.testing', 'zopefoundation/ZEO', 'zopefoundation/zope.dottedname', 'zopefoundation/zope.tal', 'zopefoundation/zope.lifecycleevent', 'zopefoundation/zope.filerepresentation', 'zopefoundation/zope.annotation', 'zopefoundation/zope.container', 'zopefoundation/zope.publisher', 'zopefoundation/zope.traversing', 'zopefoundation/zope.site', 'zopefoundation/zope.untrustedpython', 'zopefoundation/ZConfig', 'zopefoundation/zdaemon', 'zopefoundation/zope.browser', 'zopefoundation/zope.cachedescriptors', 'zopefoundation/zope.contenttype', 'zopefoundation/zope.size', 'zopefoundation/zope.tales', 'zopefoundation/z3c.csvvocabulary', 'zopefoundation/zope.minmax', 'zopefoundation/z3c.coverage', 'zopefoundation/zope.dublincore', 'zopefoundation/zope.browserresource', 'zopefoundation/zope.session', 'zopefoundation/zope.error', 'zopefoundation/zope.authentication', 'zopefoundation/zope.password', 'zopefoundation/zope.pluggableauth', 'zopefoundation/zope.securitypolicy', 'zopefoundation/zope.processlifetime', 'zopefoundation/zope.principalregistry', 'zopefoundation/zope.applicationcontrol', 'zopefoundation/zope.login', 'zopefoundation/zope.app.appsetup', 'zopefoundation/zope.app.http', 'zopefoundation/zope.pagetemplate', 'zopefoundation/zope.browsermenu', 'zopefoundation/zope.browserpage', 'zopefoundation/z3c.form', 'zopefoundation/z3c.template', 'zopefoundation/zc.sourcefactory', 'zopefoundation/zope.keyreference', 'zopefoundation/zope.intid', 'zopefoundation/z3c.recipe.sphinxdoc', 'zopefoundation/zope.viewlet', 'zopefoundation/zope.sendmail', 'zopefoundation/zope.structuredtext', 'zopefoundation/zope.principalannotation', 'zopefoundation/zope.preference', 'zopefoundation/zope.index', 'zopefoundation/zope.copypastemove', 'zopefoundation/zope.componentvocabulary', 'zopefoundation/zope.catalog', 'zopefoundation/z3c.macro', 'zopefoundation/z3c.pt', 'zopefoundation/z3c.ptcompat', 'zopefoundation/roman', 'zopefoundation/zope.app.publication', 'zopefoundation/zope.testbrowser', 'zopefoundation/z3c.table', 'zopefoundation/AccessControl', 'zopefoundation/DocumentTemplate', 'zopefoundation/Missing', 'zopefoundation/MultiMapping', 'zopefoundation/zope.ptresource', 'zopefoundation/Products.ExternalMethod', 'zopefoundation/Products.MIMETools', 'zopefoundation/zope.app.apidoc', 'zopefoundation/zope.apidoc', 'zopefoundation/Products.StandardCacheManagers', 'zopefoundation/zLOG', 'zopefoundation/zope.app.authentication', 'zopefoundation/z3c.breadcrumb', 'zopefoundation/z3c.configurator', 'zopefoundation/z3c.traverser', 'zopefoundation/zope.formlib', 'zopefoundation/z3c.testing', 'zopefoundation/zope.deferredimport', 'zopefoundation/zope.mimetype', 'zopefoundation/zope.ramcache', 'zopefoundation/zope.sequencesort', 'zopefoundation/z3c.layer.pagelet', 'zopefoundation/z3c.layer.ready2go', 'zopefoundation/keas.profile', 'zopefoundation/grokcore.component', 'zopefoundation/grokcore.annotation', 'zopefoundation/grokcore.catalog', 'zopefoundation/grok', 'zopefoundation/grokcore.chameleon', 'zopefoundation/grokcore.content', 'zopefoundation/grokcore.formlib', 'zopefoundation/grokcore.json', 'zopefoundation/grokcore.layout', 'zopefoundation/grokcore.message', 'zopefoundation/grokcore.rest', 'zopefoundation/grokcore.security', 'zopefoundation/grokcore.site', 'zopefoundation/grokcore.startup', 'zopefoundation/grokcore.traverser', 'zopefoundation/grokcore.view', 'zopefoundation/grokcore.viewlet', 'zopefoundation/grokcore.xmlrpc', 'zopefoundation/zope.errorview', 'zopefoundation/zope.fanstatic', 'zopefoundation/z3c.evalexception', 'zopefoundation/z3c.flashmessage', 'zopefoundation/zc.catalog', 'zopefoundation/zc.queue', 'zopefoundation/zope.renderer', 'zopefoundation/zope.vocabularyregistry', 'zopefoundation/five.formlib', 'zopefoundation/five.localsitemanager', 'zopefoundation/Products.ZSQLMethods', 'zopefoundation/Products.ZopeVersionControl', 'zopefoundation/z3c.checkversions', 'zopefoundation/z3c.recipe.compattest', 'zopefoundation/z3c.jbot', 'zopefoundation/zope.mkzeoinstance', 'zopefoundation/z3c.menu.ready2go', 'zopefoundation/z3c.formwidget.ckeditor', 'zopefoundation/z3c.rml', 'zopefoundation/cipher.lazydate', 'zopefoundation/zope.app.basicskin', 'zopefoundation/zope.app.broken', 'zopefoundation/zope.app.component', 'zopefoundation/zope.app.content', 'zopefoundation/zope.app.debug', 'zopefoundation/zope.app.dependable', 'zopefoundation/zope.app.error', 'zopefoundation/zope.app.exception', 'zopefoundation/zope.app.folder', 'zopefoundation/zope.app.form', 'zopefoundation/zope.app.generations', 'zopefoundation/zope.app.locales', 'zopefoundation/zope.app.localpermission', 'zopefoundation/zope.app.pagetemplate', 'zopefoundation/zope.app.principalannotation', 'zopefoundation/zope.app.publisher', 'zopefoundation/zope.app.rotterdam', 'zopefoundation/zope.app.schema', 'zopefoundation/zope.app.testing', 'zopefoundation/z3c.baseregistry', 'zopefoundation/zc.resourcelibrary', 'zopefoundation/zope.app.session', 'zopefoundation/z3c.etestbrowser', 'zopefoundation/z3c.recipe.tag', 'zopefoundation/groktoolkit', 'zopefoundation/hurry.query', 'zopefoundation/hurry.workflow', 'zopefoundation/zc.relation', 'zopefoundation/zc.relationship', 'zopefoundation/cipher.longrequest', 'zopefoundation/zc.zodbrecipes', 'zopefoundation/zc.zdaemonrecipe', 'zopefoundation/refline.srccheck', 'zopefoundation/pyramid_zope_request', 'zopefoundation/grokcore.error', 'zopefoundation/z3c.recipe.mkdir', 'zopefoundation/z3c.currency', 'zopefoundation/zc.zlibstorage', 'zopefoundation/zc.beforestorage', 'zopefoundation/zc.recipe.deployment', 'zopefoundation/z3c.sqlalchemy', 'zopefoundation/zope.schemaevent', 'zopefoundation/Products.SiteErrorLog', 'zopefoundation/z3c.relationfield', 'zopefoundation/Products.SQLAlchemyDA', 'zopefoundation/importchecker', 'zopefoundation/zc.zodbdgc', 'zopefoundation/Products.PluginRegistry', 'zopefoundation/Products.CMFUid', 'zopefoundation/z3c.formwidget.query', 'zopefoundation/zc.form', 'zopefoundation/Products.Sessions', 'zopefoundation/Products.TemporaryFolder', 'zopefoundation/zc.intid', 'zopefoundation/z3c.authviewlet', 'zopefoundation/z3c.wizard', 'zopefoundation/zodbupdate', 'zopefoundation/z3c.preference', 'zopefoundation/zope.file', 'zopefoundation/zope.app.catalog', 'zopefoundation/zope.app.onlinehelp', 'zopefoundation/zope.app.preference', 'zopefoundation/zope.app.renderer', 'zopefoundation/zope.app.tree', 'zopefoundation/zope.app.file', 'zopefoundation/megrok.strictrequire', 'zopefoundation/z3c.objpath', 'zopefoundation/zc.recipe.testrunner', 'zopefoundation/Products.ZODBMountPoint']
```

tox4-pre now does **isolated builds** - so it is not clear, whether the issues are in our packages or in tox4-pre.

I will report the issues later this week, either in our repos' issue trackers, or at the tox tracker.

**Comment by jugmac00** [comment]
# interim conclusion

I reported almost 20 issues, both in the tox and in Zope/Plone repositories.

One error cluster will be fixed, when we get a new buildout 2.13 release ( https://github.com/buildout/buildout/issues/551 ), as tox4 will use isolated builds by default and thus pulls in too new setupools version via virtualenv. The new buildout release will pin setuptools.

Another error cluster with by far the most broken tox runs, was the usage of `[]` for test collection, as this was not supported by tox 4 alpha, but only the `{posargs}` syntax. `tox4` will add support for `[]` again.

Also, there were mere broken tox builds. It is a pitty, that GHA does not offer a nice overview over all builds of an organization just as Travis did. Does anybody get notified of broken GHA builds?

The wonderful overview by @mgedmin ( https://zope3.pov.lt/py3/travis.html?filter=zope ) is also not yet updated for GHA. I do not know whether this would mean a lot of effort. I am not sure whether the badge URL is uniform or not.

So - this was a fun experiment.

Now, I will wait for both the release of the new buildout version and for the tox maintainer to fix all reported issues, and the release of a new alpha version, and the I will rerun all tox builds.

**Comment by mgedmin** [comment]
> The wonderful overview by @mgedmin ( https://zope3.pov.lt/py3/travis.html?filter=zope ) is also not yet updated for GHA. I do not know whether this would mean a lot of effort. I am not sure whether the badge URL is uniform or not.

The badge URL is uniform, I just need to find the energy to do something about it: https://github.com/ProgrammersOfVilnius/zope3.pov.lt/issues/1.

(The pandemic is not helping with my burnout.)

**Comment by jugmac00** [comment]
Take care!

**Comment by icemac** [comment]
> Does anybody get notified of broken GHA builds?

I get notified. I am not sure why but I've seen notification from broken scheduled builds, too.

**Comment by jugmac00** [comment]
> > Does anybody get notified of broken GHA builds?
> 
> I get notified. I am not sure why but I've seen notification from broken scheduled builds, too.

Maybe that is because you are in the `maintainer` group.

**Comment by dataflake** [comment]
I'm in the Maintainers group myself and have not seen any emails. I can set up a common notification email that feeds into a list on the zope.org list server so people can subscribe to it if desired. Do you want me to do that?

**Comment by jugmac00** [comment]
I would love to have a way to get notified on especially broken weekly builds. When a PR fails, well, it is up to the contributor to fix it. But anyway, I'd prefer to many notifications over none.

When we used Travis and I had half an hour time, I always looked for broken builds and tried to fix them.

**Comment by dataflake** [comment]
I have created a list "ci@zope.org" on mail.zope.org that everyone can join. We can use that as target address for CI email.

**Comment by mgedmin** [comment]
https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#github-actions-notification-options says notifications are opt-in for repositories you're watching.  (Or maybe opt-out?)

**Comment by dataflake** [comment]
I had notifications enabled, and the box checked that filters out successful runs. I unchecked that - let's see what happens.

**Comment by jugmac00** [comment]
I will speak at PyBerlin Meetup - tonight at ca. 18.50 CET about `tox`, `all-repos` and how I ran the `tox` pre-release on the almost 300 Zope repositories.

This will be a 10 minute lightning talk.

https://www.meetup.com/en-AU/PyBerlin/events/276414850/

**Comment by dataflake** [comment]
URL was wrong, fixed now. Reload the site.

**Comment by icemac** [comment]
I used https://mail.zope.org/mailman/listinfo/ci to subscribe to the new `ci` list. (This is just a remainder for me as I do not know the how to use the mailman commands via e-mail.)

**Comment by dataflake** [comment]
@icemac I think it's not clear yet if GH Actions actually support explicit email notifications to an email address that's not tied to a GH account. I'm not sure if the list is helpful at all at this point.

**Comment by icemac** [comment]
@dataflake Thank you for the clarification, I misunderstood the current status.

**Comment by jugmac00** [comment]
With the exception of the following repositories plus those without a tox.ini all Zope repositories now pass for `tox4 -e py36`:

```
    BUILDOUT_ENDLESS_LOOP = [
        "zopefoundation/zopetoolkit",  # https://github.com/zopefoundation/zopetoolkit/issues/52
        "plone/plone.memoize",  # https://github.com/plone/plone.memoize/issues/24
    ]
    BROKEN_ON_TOX3 = [
        "zopefoundation/zope.sqlalchemy",  # https://github.com/zopefoundation/zope.sqlalchemy/issues/58
        "zopefoundation/z3c.coverage",  # https://github.com/zopefoundation/z3c.coverage/issues/14
        "zopefoundation/z3c.form",  # https://github.com/zopefoundation/z3c.form/issues/102
        "zopefoundation/grokcore.site",  # https://github.com/zopefoundation/grokcore.site/issues/8
        "zopefoundation/zope.app.form",  # https://github.com/zopefoundation/zope.app.form/issues/11
        "zopefoundation/zc.resourcelibrary",  # https://github.com/zopefoundation/zc.resourcelibrary/issues/6
        "zopefoundation/zc.zlibstorage",  # https://github.com/zopefoundation/zc.zlibstorage/issues/9
        "zopefoundation/zc.relation",  # https://github.com/zopefoundation/zc.relation/issues/10
    ]
    PYTHON2_ONLY = [
        "zopefoundation/zope.untrustedpython",
    ]
    REQUIRES_MIN_PY37 = [
        "zopefoundation/z3c.rml",
    ]
    PIP_RESOLVE_ISSUE = [
        "zopefoundation/grokcore.security",  # https://github.com/zopefoundation/grokcore.security/pull/5
```

**Comment by jugmac00** [comment]
I reported all issues either at the Zope repos (see above) or at the tox repo.

Concerning `tox4` there is nothing left to do for us, as the listed broken builds (see above) have nothing to do with `tox4` and will be fixed eventually anyways.

Meanwhile @mgedmin has updated his super useful overview of all Zope repositories, so I do not think email notification, as discussed above, is really necessary any more.

https://zope3.pov.lt/py3/gha.html
