### ISSUE TITLE
config tool: What is the difference between types "buildout-recipe" and "zope-product"?

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#68]
When I read the description, they both seem to be using `zc.buildout` ...

**Comment by icemac** [comment]
* `buildout-recipe` is mostly used to test packages which are recipes used in `zc.buildout` configuration files. As the tests run in separate processes coverage must be set up in a special way.
* `zope-product` is used for packages which use `buildout` inside `tox.ini` to install themself and their dependencies – in contrast to `pure-python` where `pip` is used therefore.

Does this explanation help?
Should the documentation get updated?

**Comment by jugmac00** [comment]
Thank you! That makes it more clear.

I also had a look at the packages.txt and then on the repositories, in order to get a better understanding what is what.

I just had a look at `zope.sendmail` which is declared as a pure python project, but it still contains a `buildout.cfg`.
https://github.com/zopefoundation/zope.sendmail/blob/master/buildout.cfg

Is this a leftover?

If not, I maybe then struggle to understand the difference between `zope-product` and `pure-python` :-)

**Comment by icemac** [comment]
I did not delete all `buildout.cfg` files in the `pure-python` projects. The rule of thumb is: If they only set up the test runner and maybe coverage the are not needed any more and can get deleted. (So I did for `zope.sendmail`.)

**Comment by jugmac00** [comment]
Thank you for you explanations!

I think it is not necessary to update the documentation.

I will try to find some spare time and use the config tool to get some practice.

**Comment by mgedmin** [comment]
> If not, I maybe then struggle to understand the difference between zope-product and pure-python :-)

To me zope-product implies capital letters in the name and lineage from Zope 2 code (e.g. Producst.CMFCore), while pure-python implies lowercase letters and lineage from Zope 3 code (e.g. zope.datetime), and also no C extension modules.

**Comment by jugmac00** [comment]
If that is correct :-), then that is the most simple to follow explanation :-)

Thank you!
