### ISSUE TITLE
config-package.py shouldn't assume `tox` is in ./bin/

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/meta#73]
I already have a virtual environment that I use for things like this. I want to use it to run `config-package.py`. The documentation states that it needs a virtual environment with some things installed, and uses an example of making the current directory that virtual environment, but doesn't say that's required. I don't want to create dozens of new virtual environments just to run a tool once.

However, if you don't do that, `config-package.py` fails:
```
Traceback (most recent call last):
  File "../meta/config/config-package.py", line 270, in <module>
    call(pathlib.Path(cwd) / 'bin' / 'tox', '-p', 'auto')
  File "//meta/config/shared/call.py", line 19, in call
    args, capture_output=capture_output, text=True, cwd=cwd)
  File "//lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "//lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "//lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('//zope.site/bin/tox'): PosixPath('//zope.site/bin/tox')
```

Creating a symlink to the actual tox in a new bin/ directory worked, but is not ideal.

**Comment by icemac** [comment]
Maybe I misunderstand the problem: I only created one `venv` inside `meta/config` as documented in `REDAME.rst` and run `bin/python config-package.py` from there using the relative path to the git clone of the package to be configured. This way I do not to have to create additional venvs.
To run `tox` inside a newly configured package I use the path to the `tox` script in `meta/config` so it does not recreate the tox environments. This is not ideal and I am open to a better solution.

**Comment by jamadden** [comment]
I don't have `meta/config` as my working directory (why would I?). When I'm attempting to configure package `x`, I have `x` as my working directory.

```console
$ cd zope.site
$ python ../meta/config/config-package.py --with-pypy -t pure-python --no-push --with-docs .
```

Can we just run `tox` without assuming any directory?

**Comment by dataflake** [comment]
Just running `tox` would rely on yet another assumption, namely that `tox` is on `$PATH`. It isn't in any of my scenarios.

**Comment by mgedmin** [comment]
How about using `tox` if it exists on $PATH (`if shutil.which("tox"):`), and falling back to `./bin/tox` otherwise?

I use [pipx](https://pypi.org/project/pipx/) to have a global `tox` command. I upgrade it periodically with `pipx upgrade-all`.  If the version of my global tox differ from the one I had installed in the local venv in the meta repo chekout, then I get a lot of unnecessary recreation of tox environments between myself running tox manually and config-package.py running a different tox as part of its workflow.  (At least I think that's why the environments get recreated.)

**Comment by dataflake** [comment]
Sounds good to me.

**Comment by jamadden** [comment]
> How about using tox if it exists on $PATH (`if shutil.which("tox"):`), and falling back to `./bin/tox` otherwise?

That neatly solves my use case!
