### ISSUE TITLE
config-package.py should run the GHA tests on all pushes, not just to master

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/meta#74]
A common workflow is to open a branch and iterate on it, pushing it to github to run all the tests on all the interpreters *before* opening a pull request. The PR is only opened once the changes are complete and the CI for the branch is green.

Only running the tests when the PR is opened breaks this. Opening PRs early while still iterating produces lots of useless email notifications for anyone watching the repository.

This completely surprised me when trying to use this tool with zope.site.

**Comment by icemac** [comment]
I understand this workflow and find it convenient for changes bigger than a single commit.
On the other hand running CI for each commit on each branch causes more CI jobs to be run leading to a longer time to wait for completion and an even longer list of ran jobs below the PR.

The reason for this decision was to minimize CI runs. If it is impractical we can change it.

**Comment by jamadden** [comment]
> On the other hand running CI for each commit on each branch causes more CI jobs to be run leading to a longer time to wait for completion and an even longer list of ran jobs below the PR.

But doesn't CI just run one job when you actually push? Not one job for each commit contained in the push. Thus, the developer is in control of when and how CI jobs run based on their pushes.

**Comment by dataflake** [comment]
It only runs one job per push, that's correct. I also like to "collect" commits locally and then push them all at once to prevent long-running CI jobs. And I was also surprised about the CI configuration. I felt a bit blind several times already.

**Comment by mgedmin** [comment]
I have a question: if we build all branches and all pull request, and I push a new commit to an open PR, will we get 10 checks listed in GitHub's UI (all python versions + lint + docs), or will we get 20 checks (everything for the branch + everything for the PR)?

**Comment by dataflake** [comment]
I think we saw this doubling up for the Travis configurations.

**Comment by jamadden** [comment]
> will we get 20 checks (everything for the branch + everything for the PR)?

Yes, this. 

> I think we saw this doubling up for the Travis configurations.

We did.
