### ISSUE TITLE
config-package.py: Don't commit by default, or at least have an option not to commit

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/meta#77]
I want to review the changes before it commits them. Sometimes it takes a few iterations to get it exactly right. I want to be able to `git diff` and see what has been changed, AND I want to set the commit comment.

Scenario: Adding `ZOPE_INTERFACE_STRICT_IRO` in zope.site. It took several tries to discover the right configuration to make that happen, and I ended up with four or five commits, all with an identical comment of "Configuring for pure-python", which of course is not right.

I had to rewrite history to fix this.

**Comment by dataflake** [comment]
I am also **strongly** in favor of **not** doing any commits or pushes automatically. I work the same way: I want to look at the output of `git diff` before doing any commit, and many times I want to split changes into more than one commit and have specific commit messages.
