### ISSUE TITLE
Request for GitHub migration: zope.app.zptpage

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/meta#8]
Would anyone care to migrate zope.app.zptpage into GitHub?  (What's the current procedure for requesting migrations like this?)

**Comment by mgedmin** [comment]
I've remembered that I've a mirror of the SVN repo stashed around somewhere.

Here's https://github.com/zopefoundation/zope.app.zptpage, based on https://zope3.pov.lt/trac/browser/zope.app.zptpage.  I probably messed things up, e.g. there are no branches despite me running git svn clone --stdlayout, and I had to tag releases by hand.

**Comment by mgedmin** [comment]
Ah, the tags/branches were there in the remote/origin namespace, so didn't get pushed when I did the git push --all --tags.

I'm not sure there's any value in having them, especially given how svn's tagging means each tag lies in a little branch of its own.

**Comment by dataflake** [comment]
If no one has had any need for this package after the initial move to GitHub then surely none of this matters anymore...

**Comment by mgedmin** [comment]
I thought I had a need but in the end it turned out that I didn't! :)
