### ISSUE TITLE
meta/config: Add ability to specify commit message.

### ISSUE THREAD

**Issue by icemac** [zopefoundation/meta#82]
Currently it is possible to prevent the script from committing. To write a personal commit message.
Especially for working with multiple repositories (e. g. via `meta/config/multi-call.py`) It would be helpful to be able to specify a custom commit message. Maybe it should even be required when not using `--no-commit`.

**Comment by dataflake** [comment]
Why should a custom commit message be required when I choose `--no-commit`? Using that flag implies that I may not even want everything in a single commit.

I realize we all have different workflows, at least from my standpoint I don't see how such a requirement to specify a commit message the moment you run that script makes any sense at all.

**Comment by mgedmin** [comment]
> > Maybe it should even be required when **not** using --no-commit.

(emphasis mine)

> Why should a custom commit message be required when I choose --no-commit? 

You missed a double negative there.

Personally, +1 for allowing a `-m "Commit message"`, -0.5 for requiring it.

**Comment by dataflake** [comment]
You're right, I missed the double negation, sorry for the noise. -0.5 for requiring the custom commit message.

**Comment by dataflake** [comment]
After having used the tool on several repositories I can say this: I tend to work on repositories one by one and use `--no-commit` 100% of the time, every time. I tinker around until it's all done, then I commit myself. So with my normal usage I won't be affected.

However, if the goal is to do automated runs across multiple repositories for one common change then the option makes sense. The message could describe that one change, which is more informative than saying "I ran the tool on this repository" like we do now.
