### ISSUE TITLE
Switching to 3.8 final on Travis

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/meta#9]
Currently there are 58 repositories that build on python 3.8-dev in their .travis.yml.  I propose to run a sed script to change them all to 3.8 final and commit the updates directly to master, if there are no objections.

My plan:

```sh
cd ~/src/zopefoundation
ghcloneall
grep -l 3.8-dev */.travis.yml | xargs sed -i -e s/3.8-dev/3.8/
for d in */; do (cd $d && git commit -am "Use Python 3.8 final on Travis CI" && git push); done
```

**Comment by jugmac00** [comment]
Don't forget to signup for https://hacktoberfest.digitalocean.com/ :-)

**Comment by icemac** [comment]
Your script looks fine, go ahead and we'll see if it breaks something.

**Comment by mgedmin** [comment]
All done!

**Comment by mgedmin** [comment]
So far I don't see any new failures on https://zope3.pov.lt/py3/travis.html

(I hope I'm not getting cached images ;)

**Comment by mgedmin** [comment]
Heh, Travis CI only now finished all the build jobs.
