### ISSUE TITLE
warning: no files found matching....

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/meta#90]
When I ran all Zope repositories [with the upcoming tox4](https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/) I noticed many many warnings like `warning: no files found matching '*.bat' under directory 'docs'`.

Those warnings are issued because of a too generic `MANIFEST.IN` which was generated by our config tool.

# repro for e.g. `zope.datetime`

```
tox4 -e py36 -rvv
...
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.bat' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
warning: no files found matching '*.pt' under directory 'src'
warning: no files found matching '*.rst' under directory 'src'
warning: no files found matching '*.zcml' under directory 'src'
...
```

The warnings are only shown in verbose mode, though.

**Comment by mgedmin** [comment]
I would be in favour of making MANIFEST.in dynamic, with recursive-include docs/ *.rst *.bat conditional on --with-docs.

That would not solve including *.pt *.zcml in src/ for packages that don't ship page templates or ZCML files.  I think adding another meta.toml option just to avoid a warning is not worth it.

(I myself prefer to run `python setup.py -q sdist` in my Makefiles to avoid excessive output that hasn't been useful in my experience.)

**Comment by dataflake** [comment]
`MANIFEST.in` is already dynamic, take a look at `additional-rules` for its configuration in `meta.toml`.  Your blanket rules for docs would need slimming down, few configurations actually have `.bat` files.

**Comment by icemac** [comment]
Updating `zope.datetime` to the newest `meta/config` settings should prevent these warnings. If not, it can be fixed in the MANIFEST.in template here.
